name: intl_law_practice
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # 🔍 아래 두 줄을 추가해 주세요! 
  # (반드시 'flutter:' 보다 두 칸 안으로, 'assets:' 보다 두 칸 안으로 들여써야 합니다)
  assets:
    - assets/data/treaty_vclt.json
